import dayjs from 'dayjs';

export const mockData = [
  {
    id: 1,
    nickname: '',
    avatar_url: '',
    content: '123',
    type: 1,
    status: 1,
    created_at: dayjs().format('YYYY-MM-DD HH:mm:ss'),
  },
  {
    id: 2,
    nickname: '昵称123',
    avatar_url: '',
    content: '123',
    type: 1,
    status: 1,
    created_at: dayjs().format('YYYY-MM-DD HH:mm:ss'),
  },
  {
    id: 3,
    nickname: '',
    avatar_url: '',
    content: '123',
    type: 1,
    status: 1,
    created_at: dayjs().format('YYYY-MM-DD HH:mm:ss'),
  },
  {
    id: 4,
    nickname: '',
    avatar_url: '',
    content: '123',
    type: 1,
    status: 1,
    created_at: dayjs().format('YYYY-MM-DD HH:mm:ss'),
  },
  {
    id: 5,
    nickname: '',
    avatar_url: '',
    content: '123',
    type: 1,
    status: 1,
    created_at: dayjs().format('YYYY-MM-DD HH:mm:ss'),
  },
  {
    id: 6,
    nickname: '',
    avatar_url: '',
    content: '123\n4151525',
    type: 1,
    status: 1,
    created_at: dayjs().format('YYYY-MM-DD HH:mm:ss'),
  },
  {
    id: 7,
    nickname: '',
    avatar_url: '',
    content: '123',
    type: 1,
    status: 1,
    created_at: dayjs().format('YYYY-MM-DD HH:mm:ss'),
  },
];
